# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: unionvalue 1.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "unionvalue"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Axis Sivitz"]
  s.date = "2015-05-01"
  s.description = "Allows easy creation of immutable union values, a.k.a. sum-types.\n\nExample: \nAPICallResult = UnionValue.new(:success, :failure, :timeout)\nAPICallResult.failure.is_failure? #=> true\nAPICallResult.timeout.is_success? #=> false\nAPICallResult.success(12345).data #=> 12345\n"
  s.email = "aosivitz@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/unionvalue.rb",
    "spec/spec_helper.rb",
    "spec/unionvalue_spec.rb",
    "unionvalue.gemspec"
  ]
  s.homepage = "http://github.com/asivitz/unionvalue"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.0"
  s.summary = "Immutable union values"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.11.0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<rspec>, ["~> 2.11.0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<rspec>, ["~> 2.11.0"])
  end
end

